### ISSUE TITLE
Error compile libipatcher

### ISSUE THREAD

**Issue by salvatore8686** [brandonplank/tihmstarInstaller#4]
Bro  I can't fill out libipatcher, Two errors occur

/lib/ -L/usr/local/Cellar/libpng/1.6.37/lib -L/usr/local/Cellar/openssl@1.1/1.1.1d/lib -L/usr/local/lib -lcommon -lxpwn -lpng16 -lz /usr/local/lib/liboffsetfinder64.dylib /usr/local/lib/libimg4tool.dylib -lcompression -lssl -lcrypto /usr/local/lib/libplist.dylib /usr/local/lib/libgeneral.dylib  -g -O2 -stdlib=libc++   -install_name  /usr/local/lib/libipatcher.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module ld: library not found for -lcommon clang: error: linker command failed with exit code 1 (use -v to see invocation) make[2]: *** [libipatcher.la] Error 1 make[1]: *** [all-recursive] Error 1 make: *** [all] Error 2 Making install in libipatcher /bin/sh ../libtool  --tag=CXX   --mode=link g++  -g -O2 -stdlib=libc++ -std=c++11 -L../libipatcher -L/usr/local/lib/ -lcommon -lxpwn -L/usr/local/Cellar/libpng/1.6.37/lib -lpng16 -lz -L/usr/local/Cellar/openssl@1.1/1.1.1d/lib -lssl -lcrypto -L/usr/local/Cellar/openssl@1.1/1.1.1d/lib -L/usr/local/lib -limg4tool -lssl -lcrypto -lplist -lgeneral -L/usr/local/Cellar/openssl@1.1/1.1.1d/lib -L/usr/local/lib -loffsetfinder64 -limg4tool -lssl -lcrypto -lplist -lgeneral -L/usr/local/lib -lgeneral  -o libipatcher.la -rpath /usr/local/lib libipatcher_la-libipatcher.lo libiBoot32Patcher.la libjssy.la -L../libipatcher -L/usr/local/lib/ -lcommon -lxpwn -L/usr/local/Cellar/libpng/1.6.37/lib -lpng16 -lz -L/usr/local/Cellar/openssl@1.1/1.1.1d/lib -lssl -lcrypto -L/usr/local/Cellar/openssl@1.1/1.1.1d/lib -L/usr/local/lib -limg4tool -lssl -lcrypto -lplist -lgeneral -L/usr/local/Cellar/openssl@1.1/1.1.1d/lib -L/usr/local/lib -loffsetfinder64 -limg4tool -lssl -lcrypto -lplist -lgeneral -L/usr/local/lib -lgeneral libtool: link: g++ -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libipatcher.0.dylib  .libs/libipatcher_la-libipatcher.o   -Wl,-force_load,./.libs/libiBoot32Patcher.a -Wl,-force_load,./.libs/libjssy.a  -L../libipatcher -L/usr/local/lib/ -L/usr/local/Cellar/libpng/1.6.37/lib -L/usr/local/Cellar/openssl@1.1/1.1.1d/lib -L/usr/local/lib -lcommon -lxpwn -lpng16 -lz /usr/local/lib/liboffsetfinder64.dylib /usr/local/lib/libimg4tool.dylib -lcompression -lssl -lcrypto /usr/local/lib/libplist.dylib /usr/local/lib/libgeneral.dylib  -g -O2 -stdlib=libc++   -install_name  /usr/local/lib/libipatcher.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module ld: library not found for -lcommon clang: error: linker command failed with exit code 1 (use -v to see invocation) make[1]: *** [libipatcher.la] Error 1 make: *** [install-recursive] Error 1 aclocal: warning: couldn't open directory 'm4': No such file or directory configure.ac:6: installing './compile' configure.ac:4: installing './config.guess' configure.ac:4: installing './config.sub' configure.ac:8: installing './install-sh' configure.ac:6: error: required file './ltmain.sh' not found configure.ac:8: installing './missing' libfragmentzip/Makefile.am: installing './depcomp' aclocal: warning: couldn't open directory 'm4': No such file or directory

**Comment by BrandonPlank** [comment]
can you please screenshot the error?

**Comment by BrandonPlank** [comment]
Make sure you run tihmstarInstaller -a first to install the necessary brew dependencies.

**Comment by salvatore8686** [comment]
<img width="1427" alt="Schermata 2020-01-02 alle 01 00 54" src="https://user-images.githubusercontent.com/16167507/71647806-0413ab00-2cfc-11ea-9e13-febf4a0c8e08.png">
Following the command -a, I get the same mistakes

**Comment by BrandonPlank** [comment]
do you have xcode installed?

**Comment by salvatore8686** [comment]
Yes

**Comment by salvatore8686** [comment]
Bro  If you need me, I can give you access to my Mac by teamviewer to have

**Comment by BrandonPlank** [comment]
yes

**Comment by BrandonPlank** [comment]
dm on twitter

**Comment by BrandonPlank** [comment]
also run rm -rf /usr/local/include/xpwn/
then run tihmstarInstaller -c

**Comment by salvatore8686** [comment]
Ok test

**Comment by salvatore8686** [comment]
Bro Unfortunately, it doesn't solve

**Comment by Merculous** [comment]
Please open terminal and insert these commands:

rm -rf /usr/local/lib/libcommon.a

rm -rf /usr/local/lib/libxpwn.a

Now, remove the xpwn folder and clone my fork again.

git clone https://github.com/Merculous/xpwn.git

cd into xpwn

Run install.sh

**Comment by brandonplank** [comment]
As of right now, i am looking back into the issue. Please stand by.
